### ISSUE TITLE
Support for Unix Domain Sockets

### ISSUE THREAD

**Issue by cooldarkdryplace** [prep/beanstalk#23]
Hi!

[Beanstalkd 1.12](https://beanstalkd.github.io/2020/06/04/1.12-release-notes.html) supports Unix Domain Sockets ([commit](https://github.com/beanstalkd/beanstalkd/commit/9eab16c85d2979292bbdfb14844cd7d584340415)).

Unfortunately, the current client implementation only supports TCP sockets. Even though adding UDS support is trivial and beneficial for people who do not want to have TCP overhead.

Do you want to support UDS?
If not, please close the issue.

If yes, would you prefer just another URL prefix, like `unix://`, 
```
beanstalk.Dial("unix:///var/run/beanstalkd/beanstalkd.sock", cfg)
```
Or is your preference to give a way to construct `beanstalk.Conn` by passing `net.Conn` as a parameter?

```
conn, err := net.Dial("unix", "/var/run/beanstalkd/beanstalkd.sock")
if err != nil {
    log.Fatalf("Failed to connect: %s", err)
}
bc := beanstalk.NewConn(conn, cfg)
```

I can prepare a PR if this looks interesting.

Cheers.

**Comment by prep** [comment]
Hey buddy! Good to hear from you 🤗

I was not aware beanstalk 1.12 supported UDS and it definitely would be nice to add it. It looks like a change is needed in [ParseURI()](https://github.com/prep/beanstalk/blob/main/beanstalk.go#L23). Perhaps the function return types need to change to something like this:

```go
type uriType string

const (
  uriTCPType uriType = "tcp"
  uriTLSType uriType = "tls"
  uriUDSType uriType = "unix"
)

// XXX: Might as well unexported this function.
func parseURI(v string) (string, uriType, error) {
  // ...
}
```

So that in [Dial()](https://github.com/prep/beanstalk/blob/main/conn.go#L44) we can do something like this:

```go
func Dial(uri string, config Config) (*Conn, error) {
  addr, ut, err := ParseURI(uri)
  if err != nil {
    return nil, err
  }

  config = config.normalize()

  vat netConn net.Conn
  switch ut {
  case uriTCPType:
    // ...
  }
```

Does that make sense?

**Comment by cooldarkdryplace** [comment]
Thanks for the suggestions. I have submitted a PR.

**Comment by prep** [comment]
Thanks for the PR, bud! сливаться 👍
